### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/lua-sentencepiece#3]
@guillaumekln 
~/torchwork/lua-sentencepiece$ luarocks make lua-sentencepiece-scm-1.rockspec
-- The C compiler identification is GNU 5.4.1
-- The CXX compiler identification is GNU 5.4.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find Lua (missing: LUA_LIBRARIES) (found version "5.1.4")
Call Stack (most recent call first):
  /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.2/Modules/FindLua.cmake:167 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:6 (find_package)

-- Configuring incomplete, errors occurred!
See also "/torchwork/lua-sentencepiece/build.luarocks/CMakeFiles/CMakeOutput.log".

Error: Build error: Failed cmake.

**Comment by guillaumekln** [comment]
Someone recently got this error and solved it with:

```
sudo apt-get install libluabind-dev liblua5.1-dev
```

**Comment by guillaumekln** [comment]
I revised the `CMakeLists.txt` to also compile against `luajit` which is the default when installing Torch. The system packages above are no longer required if Torch is installed and activated.
